# This file is licensed under the terms of the MIT license https://opensource.org/license/mit
# Copyright (c) 2021-2025 Marat Reymers
# Golden config for golangci-lint v2.5.0
# Based on https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322

version: "2"

run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/joshuapare/gohivex

  golines:
    max-len: 120

  cyclop:
    max-complexity: 30
    package-average: 10.0

  depguard:
    rules:
      deprecated:
        files:
          - "$all"
        deny:
          - pkg: github.com/golang/protobuf
            desc: Use google.golang.org/protobuf instead
          - pkg: github.com/satori/go.uuid
            desc: Use github.com/google/uuid instead
          - pkg: github.com/gofrs/uuid$
            desc: Use github.com/gofrs/uuid/v5 or later
      non-test files:
        files:
          - "!$test"
        deny:
          - pkg: math/rand$
            desc: Use math/rand/v2 instead
      non-main files:
        files:
          - "!**/main.go"
        deny:
          - pkg: log$
            desc: Use log/slog instead

  errcheck:
    check-type-assertions: true

  exhaustive:
    check:
      - switch
      - map

  exhaustruct:
    exclude:
      - ^net/http.Client$
      - ^net/http.Cookie$
      - ^net/http.Request$
      - ^net/http.Response$
      - ^net/http.Server$
      - ^net/http.Transport$
      - ^net/url.URL$
      - ^os/exec.Cmd$
      - ^reflect.StructField$
    allow-empty-returns: true

  funcorder:
    struct-method: false

  funlen:
    lines: 100
    statements: 50
    ignore-comments: true

  gocognit:
    min-complexity: 20

  gocritic:
    settings:
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false

  govet:
    enable-all: true
    settings:
      shadow:
        strict: true

  nakedret:
    max-func-lines: 0

  nolintlint:
    allow-no-explanation: [funlen, gocognit, lll]
    require-explanation: true
    require-specific: true

  perfsprint:
    strconcat: false

  reassign:
    patterns:
      - ".*"

  sloglint:
    context: scope

  staticcheck:
    checks:
      - all

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - makezero
    - mirror
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

issues:
  max-same-issues: 50
  exclude-rules:
    - source: 'TODO'
      linters: [godot]
    - text: 'should have a package comment'
      linters: [revive]
    - text: 'exported \S+ \S+ should have comment( \(or a comment on this block\))? or be unexported'
      linters: [revive]
    - text: 'package comment should be of the form ".+"'
      source: '// ?(nolint|TODO)'
      linters: [revive]
    - text: 'comment on exported \S+ \S+ should be of the form ".+"'
      source: '// ?(nolint|TODO)'
      linters: [revive, staticcheck]
    - path: 'bindings/'
      linters:
        - all
