// // Code generated by c-for-go. DO NOT EDIT.
// //
// // Auto-generated bindings for libhivex.
// // Original libhivex is LGPL v2+.
// // See: https://libguestfs.org/hivex.3.html
// 

// WARNING: This file has automatically been generated on Fri, 24 Oct 2025 13:12:53 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "hivex.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

