// // Code generated by c-for-go. DO NOT EDIT.
// //
// // Auto-generated bindings for libhivex.
// // Original libhivex is LGPL v2+.
// // See: https://libguestfs.org/hivex.3.html
//

// WARNING: This file has automatically been generated on Fri, 24 Oct 2025 13:12:53 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package hivex

/*
#cgo CFLAGS: -I/opt/homebrew/include -I/usr/local/include -I/usr/include
#cgo LDFLAGS: -L/opt/homebrew/lib -L/usr/local/lib -lhivex
#include "hivex.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *HiveH) Ref() *C.hive_h {
	if x == nil {
		return nil
	}
	return (*C.hive_h)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *HiveH) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewHiveHRef converts the C object reference into a raw struct reference without wrapping.
func NewHiveHRef(ref unsafe.Pointer) *HiveH {
	return (*HiveH)(ref)
}

// NewHiveH allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewHiveH() *HiveH {
	return (*HiveH)(allocHiveHMemory(1))
}

// allocHiveHMemory allocates memory for type C.hive_h in C.
// The caller is responsible for freeing the this memory via C.free.
func allocHiveHMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfHiveHValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfHiveHValue = unsafe.Sizeof([1]C.hive_h{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *HiveH) PassRef() *C.hive_h {
	if x == nil {
		x = (*HiveH)(allocHiveHMemory(1))
	}
	return (*C.hive_h)(unsafe.Pointer(x))
}

// allocHiveSetValueMemory allocates memory for type C.hive_set_value in C.
// The caller is responsible for freeing the this memory via C.free.
func allocHiveSetValueMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfHiveSetValueValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfHiveSetValueValue = unsafe.Sizeof([1]C.hive_set_value{})

// copyPCharBytes copies the data from Go slice as *C.char.
func copyPCharBytes(slice *sliceHeader) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfCharValue) * slice.Len,
		Cap:  int(sizeOfCharValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.char)(mem0), allocs
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// allocCharMemory allocates memory for type C.char in C.
// The caller is responsible for freeing the this memory via C.free.
func allocCharMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfCharValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfCharValue = unsafe.Sizeof([1]C.char{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *HiveSetValue) Ref() *C.hive_set_value {
	if x == nil {
		return nil
	}
	return x.ref2a3d4b39
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *HiveSetValue) Free() {
	if x != nil && x.allocs2a3d4b39 != nil {
		x.allocs2a3d4b39.(*cgoAllocMap).Free()
		x.ref2a3d4b39 = nil
	}
}

// NewHiveSetValueRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewHiveSetValueRef(ref unsafe.Pointer) *HiveSetValue {
	if ref == nil {
		return nil
	}
	obj := new(HiveSetValue)
	obj.ref2a3d4b39 = (*C.hive_set_value)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *HiveSetValue) PassRef() (*C.hive_set_value, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref2a3d4b39 != nil {
		return x.ref2a3d4b39, nil
	}
	mem2a3d4b39 := allocHiveSetValueMemory(1)
	ref2a3d4b39 := (*C.hive_set_value)(mem2a3d4b39)
	allocs2a3d4b39 := new(cgoAllocMap)
	allocs2a3d4b39.Add(mem2a3d4b39)

	var ckey_allocs *cgoAllocMap
	ref2a3d4b39.key, ckey_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Key)))
	allocs2a3d4b39.Borrow(ckey_allocs)

	var ct_allocs *cgoAllocMap
	ref2a3d4b39.t, ct_allocs = (C.hive_type)(x.T), cgoAllocsUnknown
	allocs2a3d4b39.Borrow(ct_allocs)

	var clen_allocs *cgoAllocMap
	ref2a3d4b39.len, clen_allocs = (C.size_t)(x.Len), cgoAllocsUnknown
	allocs2a3d4b39.Borrow(clen_allocs)

	var cvalue_allocs *cgoAllocMap
	ref2a3d4b39.value, cvalue_allocs = copyPCharBytes((*sliceHeader)(unsafe.Pointer(&x.Value)))
	allocs2a3d4b39.Borrow(cvalue_allocs)

	x.ref2a3d4b39 = ref2a3d4b39
	x.allocs2a3d4b39 = allocs2a3d4b39
	return ref2a3d4b39, allocs2a3d4b39

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x HiveSetValue) PassValue() (C.hive_set_value, *cgoAllocMap) {
	if x.ref2a3d4b39 != nil {
		return *x.ref2a3d4b39, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *HiveSetValue) Deref() {
	if x.ref2a3d4b39 == nil {
		return
	}
	hxfc4425b := (*sliceHeader)(unsafe.Pointer(&x.Key))
	hxfc4425b.Data = unsafe.Pointer(x.ref2a3d4b39.key)
	hxfc4425b.Cap = 0x7fffffff
	// hxfc4425b.Len = ? x.Key x.ref2a3d4b39.key

	x.T = (HiveType)(x.ref2a3d4b39.t)
	x.Len = (uint64)(x.ref2a3d4b39.len)
	hxf95e7c8 := (*sliceHeader)(unsafe.Pointer(&x.Value))
	hxf95e7c8.Data = unsafe.Pointer(x.ref2a3d4b39.value)
	hxf95e7c8.Cap = 0x7fffffff
	// hxf95e7c8.Len = ? x.Value x.ref2a3d4b39.value

}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}

// copyPHiveHBytes copies the data from Go slice as *C.hive_h.
func copyPHiveHBytes(slice *sliceHeader) (*C.hive_h, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfHiveHValue) * slice.Len,
		Cap:  int(sizeOfHiveHValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.hive_h)(mem0), allocs
}

// copyPHiveTypeBytes copies the data from Go slice as *C.hive_type.
func copyPHiveTypeBytes(slice *sliceHeader) (*C.hive_type, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfHiveTypeValue) * slice.Len,
		Cap:  int(sizeOfHiveTypeValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.hive_type)(mem0), allocs
}

// allocHiveTypeMemory allocates memory for type C.hive_type in C.
// The caller is responsible for freeing the this memory via C.free.
func allocHiveTypeMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfHiveTypeValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfHiveTypeValue = unsafe.Sizeof([1]C.hive_type{})

// copyPSizeTBytes copies the data from Go slice as *C.size_t.
func copyPSizeTBytes(slice *sliceHeader) (*C.size_t, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfSizeTValue) * slice.Len,
		Cap:  int(sizeOfSizeTValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.size_t)(mem0), allocs
}

// allocSizeTMemory allocates memory for type C.size_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocSizeTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfSizeTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfSizeTValue = unsafe.Sizeof([1]C.size_t{})

const sizeOfPtr = unsafe.Sizeof(&struct{}{})

// packSSByte reads sliced Go data structure out from plain C format.
func packSSByte(v [][]byte, ptr0 **C.char) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.char)(unsafe.Pointer(ptr0)))[i0]
		hxff2234b := (*sliceHeader)(unsafe.Pointer(&v[i0]))
		hxff2234b.Data = unsafe.Pointer(ptr1)
		hxff2234b.Cap = 0x7fffffff
		// hxff2234b.Len = ?
	}
}

// unpackArgSHiveSetValue transforms a sliced Go data structure into plain C format.
func unpackArgSHiveSetValue(x []HiveSetValue) (unpacked *C.hive_set_value, allocs *cgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	allocs = new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	len0 := len(x)
	mem0 := allocHiveSetValueMemory(len0)
	allocs.Add(mem0)
	h0 := &sliceHeader{
		Data: mem0,
		Cap:  len0,
		Len:  len0,
	}
	v0 := *(*[]C.hive_set_value)(unsafe.Pointer(h0))
	for i0 := range x {
		allocs0 := new(cgoAllocMap)
		v0[i0], allocs0 = x[i0].PassValue()
		allocs.Borrow(allocs0)
	}
	h := (*sliceHeader)(unsafe.Pointer(&v0))
	unpacked = (*C.hive_set_value)(h.Data)
	return
}

// packSHiveSetValue reads sliced Go data structure out from plain C format.
func packSHiveSetValue(v []HiveSetValue, ptr0 *C.hive_set_value) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfHiveSetValueValue]C.hive_set_value)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = *NewHiveSetValueRef(unsafe.Pointer(&ptr1))
	}
}
