// // Code generated by c-for-go. DO NOT EDIT.
// //
// // Auto-generated bindings for libhivex.
// // Original libhivex is LGPL v2+.
// // See: https://libguestfs.org/hivex.3.html
//

// WARNING: This file has automatically been generated on Fri, 24 Oct 2025 13:12:53 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package hivex

/*
#cgo CFLAGS: -I/opt/homebrew/include -I/usr/local/include -I/usr/include
#cgo LDFLAGS: -L/opt/homebrew/lib -L/usr/local/lib -lhivex
#include "hivex.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// HIVEXH_ as defined in include/hivex.h:28

	// HIVEXNOKEY as defined in include/hivex.h:50
	HIVEXNOKEY = 0x104a6cd30
	// HIVEXOPENVERBOSE as defined in include/hivex.h:109
	HIVEXOPENVERBOSE = 1
	// HIVEXOPENDEBUG as defined in include/hivex.h:111
	HIVEXOPENDEBUG = 2
	// HIVEXOPENWRITE as defined in include/hivex.h:113
	HIVEXOPENWRITE = 4
	// HIVEXOPENUNSAFE as defined in include/hivex.h:115
	HIVEXOPENUNSAFE = 8
	// HIVEXVISITSKIPBAD as defined in include/hivex.h:177
	HIVEXVISITSKIPBAD = 1
)

// HiveType as declared in include/hivex.h:105
type HiveType int32

// HiveType enumeration from include/hivex.h:105
const ()

const ()
