// // Code generated by c-for-go. DO NOT EDIT.
// //
// // Auto-generated bindings for libhivex.
// // Original libhivex is LGPL v2+.
// // See: https://libguestfs.org/hivex.3.html
//

// WARNING: This file has automatically been generated on Fri, 24 Oct 2025 13:12:53 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package hivex provides CGO bindings for libhivex.

libhivex is a C library for reading and writing Windows Registry "hive" files.
These files are used by Windows to store the system registry data.

This package is auto-generated using c-for-go from the libhivex C headers.

Original libhivex: https://libguestfs.org/hivex.3.html
License: LGPL v2+
*/
package hivex
