// // Code generated by c-for-go. DO NOT EDIT.
// //
// // Auto-generated bindings for libhivex.
// // Original libhivex is LGPL v2+.
// // See: https://libguestfs.org/hivex.3.html
//

// WARNING: This file has automatically been generated on Fri, 24 Oct 2025 13:12:53 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package hivex

/*
#cgo CFLAGS: -I/opt/homebrew/include -I/usr/local/include -I/usr/include
#cgo LDFLAGS: -L/opt/homebrew/lib -L/usr/local/lib -lhivex
#include "hivex.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// HivexOpen function as declared in include/hivex.h:127
func HivexOpen(Filename string, Flags int32) []HiveH {
	cFilename, cFilenameAllocMap := unpackPCharString(Filename)
	cFlags, cFlagsAllocMap := (C.int)(Flags), cgoAllocsUnknown
	__ret := C.hivex_open(cFilename, cFlags)
	runtime.KeepAlive(cFlagsAllocMap)
	runtime.KeepAlive(cFilenameAllocMap)
	__v := (*(*[0x7fffffff]HiveH)(unsafe.Pointer(__ret)))[:0]
	return __v
}

// HivexClose function as declared in include/hivex.h:128
func HivexClose(H []HiveH) int32 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	__ret := C.hivex_close(cH)
	runtime.KeepAlive(cHAllocMap)
	__v := (int32)(__ret)
	return __v
}

// HivexRoot function as declared in include/hivex.h:129
func HivexRoot(H []HiveH) HiveNodeH {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	__ret := C.hivex_root(cH)
	runtime.KeepAlive(cHAllocMap)
	__v := (HiveNodeH)(__ret)
	return __v
}

// HivexLastModified function as declared in include/hivex.h:130
func HivexLastModified(H []HiveH) int64 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	__ret := C.hivex_last_modified(cH)
	runtime.KeepAlive(cHAllocMap)
	__v := (int64)(__ret)
	return __v
}

// HivexNodeName function as declared in include/hivex.h:131
func HivexNodeName(H []HiveH, Node HiveNodeH) []byte {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_name(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (*(*[0x7fffffff]byte)(unsafe.Pointer(__ret)))[:0]
	return __v
}

// HivexNodeNameLen function as declared in include/hivex.h:132
func HivexNodeNameLen(H []HiveH, Node HiveNodeH) uint64 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_name_len(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (uint64)(__ret)
	return __v
}

// HivexNodeTimestamp function as declared in include/hivex.h:133
func HivexNodeTimestamp(H []HiveH, Node HiveNodeH) int64 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_timestamp(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (int64)(__ret)
	return __v
}

// HivexNodeChildren function as declared in include/hivex.h:134
func HivexNodeChildren(H []HiveH, Node HiveNodeH) []HiveNodeH {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_children(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (*(*[0x7fffffff]HiveNodeH)(unsafe.Pointer(__ret)))[:0]
	return __v
}

// HivexNodeGetChild function as declared in include/hivex.h:135
func HivexNodeGetChild(H []HiveH, Node HiveNodeH, Name string) HiveNodeH {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	cName, cNameAllocMap := unpackPCharString(Name)
	__ret := C.hivex_node_get_child(cH, cNode, cName)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (HiveNodeH)(__ret)
	return __v
}

// HivexNodeNrChildren function as declared in include/hivex.h:136
func HivexNodeNrChildren(H []HiveH, Node HiveNodeH) uint64 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_nr_children(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (uint64)(__ret)
	return __v
}

// HivexNodeParent function as declared in include/hivex.h:137
func HivexNodeParent(H []HiveH, Node HiveNodeH) HiveNodeH {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_parent(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (HiveNodeH)(__ret)
	return __v
}

// HivexNodeValues function as declared in include/hivex.h:138
func HivexNodeValues(H []HiveH, Node HiveNodeH) []HiveValueH {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_values(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (*(*[0x7fffffff]HiveValueH)(unsafe.Pointer(__ret)))[:0]
	return __v
}

// HivexNodeGetValue function as declared in include/hivex.h:139
func HivexNodeGetValue(H []HiveH, Node HiveNodeH, Key string) HiveValueH {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	cKey, cKeyAllocMap := unpackPCharString(Key)
	__ret := C.hivex_node_get_value(cH, cNode, cKey)
	runtime.KeepAlive(cKeyAllocMap)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (HiveValueH)(__ret)
	return __v
}

// HivexNodeNrValues function as declared in include/hivex.h:140
func HivexNodeNrValues(H []HiveH, Node HiveNodeH) uint64 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_nr_values(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (uint64)(__ret)
	return __v
}

// HivexValueKeyLen function as declared in include/hivex.h:141
func HivexValueKeyLen(H []HiveH, Val HiveValueH) uint64 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	__ret := C.hivex_value_key_len(cH, cVal)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (uint64)(__ret)
	return __v
}

// HivexValueKey function as declared in include/hivex.h:142
func HivexValueKey(H []HiveH, Val HiveValueH) []byte {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	__ret := C.hivex_value_key(cH, cVal)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (*(*[0x7fffffff]byte)(unsafe.Pointer(__ret)))[:0]
	return __v
}

// HivexValueType function as declared in include/hivex.h:143
func HivexValueType(H []HiveH, Val HiveValueH, T []HiveType, Len []uint64) int32 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	cT, cTAllocMap := (*C.hive_type)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&T)).Data)), cgoAllocsUnknown
	cLen, cLenAllocMap := (*C.size_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Len)).Data)), cgoAllocsUnknown
	__ret := C.hivex_value_type(cH, cVal, cT, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cTAllocMap)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (int32)(__ret)
	return __v
}

// HivexNodeStructLength function as declared in include/hivex.h:144
func HivexNodeStructLength(H []HiveH, Node HiveNodeH) uint64 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_struct_length(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (uint64)(__ret)
	return __v
}

// HivexValueStructLength function as declared in include/hivex.h:145
func HivexValueStructLength(H []HiveH, Val HiveValueH) uint64 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	__ret := C.hivex_value_struct_length(cH, cVal)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (uint64)(__ret)
	return __v
}

// HivexValueDataCellOffset function as declared in include/hivex.h:146
func HivexValueDataCellOffset(H []HiveH, Val HiveValueH, Len []uint64) HiveValueH {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	cLen, cLenAllocMap := (*C.size_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Len)).Data)), cgoAllocsUnknown
	__ret := C.hivex_value_data_cell_offset(cH, cVal, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (HiveValueH)(__ret)
	return __v
}

// HivexValueValue function as declared in include/hivex.h:147
func HivexValueValue(H []HiveH, Val HiveValueH, T []HiveType, Len []uint64) []byte {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	cT, cTAllocMap := (*C.hive_type)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&T)).Data)), cgoAllocsUnknown
	cLen, cLenAllocMap := (*C.size_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Len)).Data)), cgoAllocsUnknown
	__ret := C.hivex_value_value(cH, cVal, cT, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cTAllocMap)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (*(*[0x7fffffff]byte)(unsafe.Pointer(__ret)))[:0]
	return __v
}

// HivexValueString function as declared in include/hivex.h:148
func HivexValueString(H []HiveH, Val HiveValueH) []byte {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	__ret := C.hivex_value_string(cH, cVal)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (*(*[0x7fffffff]byte)(unsafe.Pointer(__ret)))[:0]
	return __v
}

// HivexValueMultipleStrings function as declared in include/hivex.h:149
func HivexValueMultipleStrings(H []HiveH, Val HiveValueH) [][]byte {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	__ret := C.hivex_value_multiple_strings(cH, cVal)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	var __v [][]byte
	packSSByte(__v, __ret)
	return __v
}

// HivexValueDword function as declared in include/hivex.h:150
func HivexValueDword(H []HiveH, Val HiveValueH) int32 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	__ret := C.hivex_value_dword(cH, cVal)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (int32)(__ret)
	return __v
}

// HivexValueQword function as declared in include/hivex.h:151
func HivexValueQword(H []HiveH, Val HiveValueH) int64 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cVal, cValAllocMap := (C.hive_value_h)(Val), cgoAllocsUnknown
	__ret := C.hivex_value_qword(cH, cVal)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (int64)(__ret)
	return __v
}

// HivexCommit function as declared in include/hivex.h:152
func HivexCommit(H []HiveH, Filename string, Flags int32) int32 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cFilename, cFilenameAllocMap := unpackPCharString(Filename)
	cFlags, cFlagsAllocMap := (C.int)(Flags), cgoAllocsUnknown
	__ret := C.hivex_commit(cH, cFilename, cFlags)
	runtime.KeepAlive(cFlagsAllocMap)
	runtime.KeepAlive(cFilenameAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (int32)(__ret)
	return __v
}

// HivexNodeAddChild function as declared in include/hivex.h:153
func HivexNodeAddChild(H []HiveH, Parent HiveNodeH, Name string) HiveNodeH {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cParent, cParentAllocMap := (C.hive_node_h)(Parent), cgoAllocsUnknown
	cName, cNameAllocMap := unpackPCharString(Name)
	__ret := C.hivex_node_add_child(cH, cParent, cName)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cParentAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (HiveNodeH)(__ret)
	return __v
}

// HivexNodeDeleteChild function as declared in include/hivex.h:154
func HivexNodeDeleteChild(H []HiveH, Node HiveNodeH) int32 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	__ret := C.hivex_node_delete_child(cH, cNode)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (int32)(__ret)
	return __v
}

// HivexNodeSetValues function as declared in include/hivex.h:155
func HivexNodeSetValues(H []HiveH, Node HiveNodeH, NrValues uint64, Values []HiveSetValue, Flags int32) int32 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	cNrValues, cNrValuesAllocMap := (C.size_t)(NrValues), cgoAllocsUnknown
	cValues, cValuesAllocMap := unpackArgSHiveSetValue(Values)
	cFlags, cFlagsAllocMap := (C.int)(Flags), cgoAllocsUnknown
	__ret := C.hivex_node_set_values(cH, cNode, cNrValues, cValues, cFlags)
	runtime.KeepAlive(cFlagsAllocMap)
	packSHiveSetValue(Values, cValues)
	runtime.KeepAlive(cValuesAllocMap)
	runtime.KeepAlive(cNrValuesAllocMap)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (int32)(__ret)
	return __v
}

// HivexNodeSetValue function as declared in include/hivex.h:156
func HivexNodeSetValue(H []HiveH, Node HiveNodeH, Val []HiveSetValue, Flags int32) int32 {
	cH, cHAllocMap := (*C.hive_h)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&H)).Data)), cgoAllocsUnknown
	cNode, cNodeAllocMap := (C.hive_node_h)(Node), cgoAllocsUnknown
	cVal, cValAllocMap := unpackArgSHiveSetValue(Val)
	cFlags, cFlagsAllocMap := (C.int)(Flags), cgoAllocsUnknown
	__ret := C.hivex_node_set_value(cH, cNode, cVal, cFlags)
	runtime.KeepAlive(cFlagsAllocMap)
	packSHiveSetValue(Val, cVal)
	runtime.KeepAlive(cValAllocMap)
	runtime.KeepAlive(cNodeAllocMap)
	runtime.KeepAlive(cHAllocMap)
	__v := (int32)(__ret)
	return __v
}
