// // Code generated by c-for-go. DO NOT EDIT.
// //
// // Auto-generated bindings for libhivex.
// // Original libhivex is LGPL v2+.
// // See: https://libguestfs.org/hivex.3.html
//

// WARNING: This file has automatically been generated on Fri, 24 Oct 2025 13:12:53 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package hivex

/*
#cgo CFLAGS: -I/opt/homebrew/include -I/usr/local/include -I/usr/include
#cgo LDFLAGS: -L/opt/homebrew/lib -L/usr/local/lib -lhivex
#include "hivex.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// HiveH as declared in include/hivex.h:40
type HiveH C.hive_h

// HiveNodeH type as declared in include/hivex.h:43
type HiveNodeH uint64

// HiveValueH type as declared in include/hivex.h:44
type HiveValueH uint64

// HiveSetValue as declared in include/hivex.h:124
type HiveSetValue struct {
	Key            []byte
	T              HiveType
	Len            uint64
	Value          []byte
	ref2a3d4b39    *C.hive_set_value
	allocs2a3d4b39 interface{}
}
